### ISSUE TITLE
KeyError: 'canvas' when loading

### ISSUE THREAD

**Issue by jasoncow007** [Chaest/sd-webui-sc-loader#4]
Traceback (most recent call last):
  File "D:\sd-webui-aki-v4\py310\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\sd-webui-aki-v4\py310\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "D:\sd-webui-aki-v4\py310\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\sd-webui-aki-v4\py310\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\sd-webui-aki-v4\py310\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "D:\sd-webui-aki-v4\py310\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "D:\sd-webui-aki-v4\py310\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "D:\sd-webui-aki-v4\extensions\sd-webui-sc-loader\sc_loader\process\latent\tensor.py", line 15, in do_visualize
    from_sc_pose(pose, payload)
  File "D:\sd-webui-aki-v4\extensions\sd-webui-sc-loader\sc_loader\openpose\sc_pose\convert.py", line 19, in from_sc_pose
    w, h = data['canvas']['width'], data['canvas']['height']
KeyError: 'canvas'
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

**Comment by Chaest** [comment]
Hi @jasoncow007, could you please give me a bit more info on the inputs?
It appears you are providing a yaml pose (i.e. sc pose) but it does not seem to have the right format. Can you elaborate on that?

**Comment by Chaest** [comment]
I'm closing for now, please reopen if need be.
